version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4173:4173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev -- --host"

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    command: flask run --host=0.0.0.0

volumes:
  frontend_node_modules:
